### PR TITLE
[OCPBUGS-45069] Add a check for manila share type

### PR DESCRIPTION
**Pull request by itzikb-redhat**
If the share type extra spec of driver_handles_share_servers is true we skip the test.

### CODE REVIEW

**Comment by rlobillo** [comment]
> If the share type extra spec of driver_handles_share_servers is true we skip the test.

Hi @itzikb-redhat.

Could you please elaborate why having `driver_handles_share_servers` set to `false` is a requirement? Do you know if that is documented somewhere? I took a look at the limitations and couldn't find it:

https://docs.openshift.com/container-platform/4.17/storage/container_storage_interface/persistent-storage-csi-manila.html#persistent-storage-csi-manila-limitations_persistent-storage-csi-manila

Maybe should be added there?

**Comment by MiguelCarpio** [comment]
Hi @rlobillo @itzikb-redhat 

The test should validate if the `driver_handles_share_servers` is set to `true` or `false`, and in that way use the `share-network` or not.
* true --> Get the `share-network` (or create it and add it to the compute nodes) and use it to create the `manila-pvc`
* false --> Create the `manila-pvc` without a `share-network`

You can find in the following [documentation](https://docs.redhat.com/en/documentation/red_hat_openstack_platform/17.1/html/configuring_persistent_storage/assembly_manila-performing-operations-with-the-shared-file-systems-service_assembly-swift#ref_creating-nfs-cephfs-or-cifs-shares_performing-operations-with-manila) the requirements and what is supported to create a `manila-pvc` (or `share`):

<share_network>: The name of the share network:
* Required if the share type has driver_handles_share_servers set to true.
* Unsupported if the share type has driver_handles_share_servers set to false.
* Unsupported for CephFS-NFS and native CephFS. These protocols do not support share types that have driver_handles_share_servers set to true.

If this test is oriented to create a `manila-pvc` not using a `share-network`, it should skip when finding the `driver_handles_share_servers` is set to `true`.

**Comment by rlobillo** [comment]
> Hi @rlobillo @itzikb-redhat
> 
> The test should validate if the `driver_handles_share_servers` is set to `true` or `false`, and in that way use the `share-network` or not.
> 
> * true --> Get the `share-network` (or create it and add it to the compute nodes) and use it to create the `manila-pvc`
> * false --> Create the `manila-pvc` without a `share-network`
> 

In our CI we are using below share type:
```
$ openstack share type show default
+----------------------+--------------------------------------+
| Field                | Value                                |
+----------------------+--------------------------------------+
| id                   | c0b38029-e7ab-48c3-bc2a-522237fcf89d |
| name                 | default                              |
| visibility           | public                               |
| is_default           | True                                 |
| required_extra_specs | driver_handles_share_servers : False |
| optional_extra_specs | snapshot_support : True              |
| description          | None                                 |
+----------------------+--------------------------------------+
```

and the test is passing. I believe that feature "driver_handles_share_servers" (also known as DHSS) is for instructing the backend to use different set of storage servers. We are not testing that AFAIK.

**Comment by rlobillo** [comment]
I wonder if we should create a separate test then covering the `DHSS=true` case.

**Comment by MiguelCarpio** [comment]
> > Hi @rlobillo @itzikb-redhat
> > The test should validate if the `driver_handles_share_servers` is set to `true` or `false`, and in that way use the `share-network` or not.
> > 
> > * true --> Get the `share-network` (or create it and add it to the compute nodes) and use it to create the `manila-pvc`
> > * false --> Create the `manila-pvc` without a `share-network`
> 
> Thanks @MiguelCarpio! I still have my concerns about this. In our CI we are using below share type:
> 
> ```
> $ openstack share type show default
> +----------------------+--------------------------------------+
> | Field                | Value                                |
> +----------------------+--------------------------------------+
> | id                   | c0b38029-e7ab-48c3-bc2a-522237fcf89d |
> | name                 | default                              |
> | visibility           | public                               |
> | is_default           | True                                 |
> | required_extra_specs | driver_handles_share_servers : False |
> | optional_extra_specs | snapshot_support : True              |
> | description          | None                                 |
> +----------------------+--------------------------------------+
> ```
> 
> and the test is passing. I believe that feature "driver_handles_share_servers" (also known as DHSS) is for instructing the backend to use different set of storage servers. We are not testing that AFAIK.

Yes, it passes because with `driver_handles_share_servers` set to `false` doesn't need a `share-network` to create a `manila-pvc`

**Comment by rlobillo** [comment]
@itzikb-redhat I think it would be good to have a comment in the test itself with a link to the doc bug that explains this limitation.

/hold

**Comment by EmilienM** [comment]
We should backport it.

**Pull request merged**
