### PR TITLE
Improve load-balancer health monitor tests

### PR DESCRIPTION
**Pull request by MaysaMacedo**
When a cluster only has one worker node, the pods get scheduled
in this worker node by default. In the case of ETP:local test
the requested two Pods were scheduled in the same worker node,
consequently only one LB member had ACTIVE state due to health monitors
and the test expected for two ACTIVE members. This commit fixes the issue by
ensuring that the amount of worker nodes is taken into consideration
when defining the amount of Pod replicas.

### CODE REVIEW

**Comment by eurijon** [comment]
Hey @MaysaMacedo, shouldn't be two members if the svc is backed by two pods (even in one master node deployment)?

**Comment by MaysaMacedo** [comment]
@rlobillo even if the cluster does not have only one worker node, it's possible that the two Pods gets scheduled in the same worker node. We need to add protection for this case, which is missing in this PR, so I will add hold until I fix it.

/hold

**Comment by eurijon** [comment]
@MaysaMacedo ack, it makes sense yep, as the LB monitors the nodeports and not the pods

**Review by mandre — COMMENTED** [review]
thanks!
/lgtm
/approve

**Pull request merged**
