### PR TITLE
Rebase on openshift/origin

### PR DESCRIPTION
**Pull request by pierreprinetti**
And other bumps

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Failures so far look a lot like infrastructure issues

/retest

**Comment by pierreprinetti** [comment]
-_-
/retest

**Comment by pierreprinetti** [comment]
>Suite run returned error: suite "openshift/openstack" does not contain any tests

**Comment by rlobillo** [comment]
/close

I re-used and pre-existent branch by mistake

**Comment by rlobillo** [comment]
Please refer to https://github.com/openshift/openstack-test/pull/189

**Pull request closed without merging**
