### PR TITLE
Upgrade origin to commit 8db5731e8d007d00c096567a87653e731b2da015

### PR DESCRIPTION
**Pull request by pierreprinetti**
Also:
* wire context.Context for cancellation across the OpenStack tests, to fulfill the Kubernetes dependencies
* Bump Gophercloud to v1.4.0

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Depends on https://github.com/openshift/release/pull/40223

**Comment by pierreprinetti** [comment]
🎉

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
