### PR TITLE
Use Origin's release-4.10 as a dependency

### PR DESCRIPTION
**Pull request by pierreprinetti**
Using commit https://github.com/openshift/origin/commit/1d82b3ccec679a0c15413d7b6068f1dac42e26d0 as a base.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Depends on https://github.com/openshift/release/pull/35525

**Comment by pierreprinetti** [comment]
Depends on https://github.com/openshift/release/pull/35530

**Comment by pierreprinetti** [comment]
Good to go!
/cc itzikb-redhat mandre rlobillo

**Review by mandre — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
