### PR TITLE
Resize PVCs for prometheus

### PR DESCRIPTION
**Pull request by rlobillo**
Automation for customer case:
https://access.redhat.com/support/cases/#/case/03081641
https://access.redhat.com/solutions/5325711

### CODE REVIEW

**Comment by rlobillo** [comment]
@EmilienM FYI

**Comment by EmilienM** [comment]
nicely done! I didn't see the test [running](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_openstack-test/24/pull-ci-openshift-openstack-test-main-test/1525059437209849856/artifacts/test/openstack-test-openstack/build-log.txt), what do I miss?

**Comment by EmilienM** [comment]
nicely done! I didn't see the test [running](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_openstack-test/24/pull-ci-openshift-openstack-test-main-test/1525059437209849856/artifacts/test/openstack-test-openstack/build-log.txt), what do I miss?

**Comment by pierreprinetti** [comment]
/hold
The new test is still not there

**Comment by pierreprinetti** [comment]
A locally-built binary behaves well. This has to be a CI issue

```shell
$ make openstack-tests && ./openstack-tests run --dry-run --run '\[Feature:openstack\]' openshift/conformance
go build -o openstack-tests ./cmd/openshift-tests
"[sig-installer][Feature:openstack] The OpenStack platform creates Control plane nodes in a server group [Suite:openshift/conformance/parallel]"
"[sig-installer][Feature:openstack] The OpenStack platform creates Control plane nodes on separate hosts when serverGroupPolicy is anti-affinity [Suite:openshift/conformance/parallel]"
"[sig-installer][Feature:openstack] The OpenStack platform creates Worker nodes in a server group [Suite:openshift/conformance/parallel]"
"[sig-installer][Feature:openstack] The OpenStack platform creates Worker nodes on separate hosts when serverGroupPolicy is anti-affinity [Suite:openshift/conformance/parallel]"
"[sig-installer][Feature:openstack] The OpenStack platform on instance creation should follow machineset specs [Suite:openshift/conformance/parallel]"
"[sig-installer][Feature:openstack] The OpenStack platform on instance creation should include the addresses on the machine specs [Suite:openshift/conformance/parallel]"
"[sig-installer][Feature:openstack] The OpenStack platform on volume creation should follow PVC specs during resizing for prometheus [Suite:openshift/conformance/parallel]"
```

**Comment by pierreprinetti** [comment]
The test passes in a local build.

Enabled Prometheus persistent storage by applying:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
data:
  config.yaml: |
    prometheusK8s:
      volumeClaimTemplate:
        spec:
          #storageClassName: <undefined will use the default storageClass>
          resources:
            requests:
              storage: 2Gi
```

Without it, the test skips.

@rlobillo: Does it make sense to enable persistent storage in the test, and restore the previous state after the test?

**Comment by rlobillo** [comment]
@pierreprinetti I tried to restore the previous status (by removing the cm from the cluster) and it wasn't working, the PVCs were not removed. I did not find in documentation a way to restore the change so I assumed that is a path of no return.

I submitted a patch in our automation (D/S CI) to enable this cm right after the installation, so our jobs in D/S will run the test.

**Comment by pierreprinetti** [comment]
Understood. The monitoring team seems to confirm your suspicion. LGTM! Please rebase and we're good to go

**Review by pierreprinetti — APPROVED** [review]

**Pull request merged**
