### PR TITLE
Rebase on Origin release-4.12

### PR DESCRIPTION
**Pull request by pierreprinetti**
* Rebase on Kubernetes v1.25
* Depend on machine v1alpha1 from openshift/api
* Migrate to ginkgo v2

### CODE REVIEW

**Comment by dulek** [comment]
Kuryr test failures are kinda expected, we have 4.13 broken at the moment. Regular test failures look genuine though. @rlobillo

**Comment by rlobillo** [comment]
@pierreprinetti I can see in the logs this:

`Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1000710000, 1000719999]`

In the rebased version, it is setting the ID to 1000 as the behaviour os the library changed: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/framework/pod/utils.go#L134

I will check next week how to set a correct value there.

**Comment by dulek** [comment]
Thanks @rlobillo! Kuryr job failure is expected until openshift/cluster-network-operator#1669 gets in.
/lgtm
/override e2e-openstack-kuryr

Leaving approval for @pierreprinetti.

**Comment by pierreprinetti** [comment]
Thank you @rlobillo!
/approve

**Pull request merged**
