### PR TITLE
Bump origin

### PR DESCRIPTION
**Pull request by pierreprinetti**
Rebase onto the latest origin commit. Bump Go to v1.18.

### CODE REVIEW

**Comment by pierreprinetti** [comment]
Depends on https://github.com/openshift/release/pull/31189

**Comment by pierreprinetti** [comment]
/hold
TODO: investigate the test failure.

**Comment by pierreprinetti** [comment]
/hold cancel
I had forgot to refresh the generated list of tests after bumping origin.

**Comment by MaysaMacedo** [comment]
I see the following error:
`error: image "k8s.gcr.io/e2e-test-images/agnhost:2.39" defines index 1 but is defined upstream as "k8s.gcr.io/e2e-test-images/agnhost:2.36", must be fixed in test/extended/util/image`

I'm not sure where "k8s.gcr.io/e2e-test-images/agnhost:2.36" is being used

**Comment by pierreprinetti** [comment]
The [error](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_openstack-test/47/pull-ci-openshift-openstack-test-main-test-kuryr/1560558000643510272) might be legit, but likely not related to this change.

/retest

**Comment by dulek** [comment]
/restest

These are unrelated.

**Comment by pierreprinetti** [comment]
The same test fails with ‘Test Panicked: assignment to entry in nil map
Ginkgo exit error 1: exit with code 1}’ now.

**Comment by dulek** [comment]
> The same test (`[sig-installer][Suite:openshift/openstack][Kuryr] Kuryr should create a subnet for a namespace only when a pod without hostNetwork is created in the namespace [Suite:openshift/conformance/parallel]`) now fails with:
> 
> ```
> {  fail [runtime/map_faststr.go:205]: Test Panicked: assignment to entry in nil map
> Ginkgo exit error 1: exit with code 1}
> ```

Obviously Friday evening isn't best for coding. ;) Checking.

**Comment by dulek** [comment]
Let's see now.

**Comment by dulek** [comment]
Aw, fixed this yesterday, but forgot to send the patch out, it seems?

**Comment by pierreprinetti** [comment]
Great, thanks @dulek !

/approve

**Comment by dulek** [comment]
> Great, thanks @dulek !
> 
> /approve

Took me a while, but I swear I was sure I pushed the update yesterday. ;)

**Pull request merged**
